//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/battleground.proto
// Note: requires additional types generated from: common.proto
namespace proto.battleground
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqMatchBattleground")]
  public partial class ReqMatchBattleground : global::ProtoBuf.IExtensible
  {
    public ReqMatchBattleground() {}
    
    private uint _mapid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspMatchBattleground")]
  public partial class RspMatchBattleground : global::ProtoBuf.IExtensible
  {
    public RspMatchBattleground() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCancelMatchBattleground")]
  public partial class ReqCancelMatchBattleground : global::ProtoBuf.IExtensible
  {
    public ReqCancelMatchBattleground() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspCancelMatchBattleground")]
  public partial class RspCancelMatchBattleground : global::ProtoBuf.IExtensible
  {
    public RspCancelMatchBattleground() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyMatchComplete")]
  public partial class NotifyMatchComplete : global::ProtoBuf.IExtensible
  {
    public NotifyMatchComplete() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqStartBattleground")]
  public partial class ReqStartBattleground : global::ProtoBuf.IExtensible
  {
    public ReqStartBattleground() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspStartBattleground")]
  public partial class RspStartBattleground : global::ProtoBuf.IExtensible
  {
    public RspStartBattleground() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RepEnterBattleground")]
  public partial class RepEnterBattleground : global::ProtoBuf.IExtensible
  {
    public RepEnterBattleground() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyPlayerEnterBattleground")]
  public partial class NotifyPlayerEnterBattleground : global::ProtoBuf.IExtensible
  {
    public NotifyPlayerEnterBattleground() {}
    
    private readonly global::System.Collections.Generic.List<common.CharacterDTO> _chs = new global::System.Collections.Generic.List<common.CharacterDTO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"chs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<common.CharacterDTO> chs
    {
      get { return _chs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqExitBattleground")]
  public partial class ReqExitBattleground : global::ProtoBuf.IExtensible
  {
    public ReqExitBattleground() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspExitBattleground")]
  public partial class RspExitBattleground : global::ProtoBuf.IExtensible
  {
    public RspExitBattleground() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyExitBattleground")]
  public partial class NotifyExitBattleground : global::ProtoBuf.IExtensible
  {
    public NotifyExitBattleground() {}
    
    private uint _characterid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}