//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/battlearena.proto
// Note: requires additional types generated from: common.proto
namespace proto.battlearena
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqMatchArena")]
  public partial class ReqMatchArena : global::ProtoBuf.IExtensible
  {
    public ReqMatchArena() {}
    
    private uint _mapid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspMatchArena")]
  public partial class RspMatchArena : global::ProtoBuf.IExtensible
  {
    public RspMatchArena() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCancelMatchArena")]
  public partial class ReqCancelMatchArena : global::ProtoBuf.IExtensible
  {
    public ReqCancelMatchArena() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspCancelMatchArena")]
  public partial class RspCancelMatchArena : global::ProtoBuf.IExtensible
  {
    public RspCancelMatchArena() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyMatchComplete")]
  public partial class NotifyMatchComplete : global::ProtoBuf.IExtensible
  {
    public NotifyMatchComplete() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqStartArena")]
  public partial class ReqStartArena : global::ProtoBuf.IExtensible
  {
    public ReqStartArena() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspStartArena")]
  public partial class RspStartArena : global::ProtoBuf.IExtensible
  {
    public RspStartArena() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RepEnterArena")]
  public partial class RepEnterArena : global::ProtoBuf.IExtensible
  {
    public RepEnterArena() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyPlayerEnterArena")]
  public partial class NotifyPlayerEnterArena : global::ProtoBuf.IExtensible
  {
    public NotifyPlayerEnterArena() {}
    
    private readonly global::System.Collections.Generic.List<common.CharacterDTO> _chs = new global::System.Collections.Generic.List<common.CharacterDTO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"chs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<common.CharacterDTO> chs
    {
      get { return _chs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqExitArena")]
  public partial class ReqExitArena : global::ProtoBuf.IExtensible
  {
    public ReqExitArena() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspExitArena")]
  public partial class RspExitArena : global::ProtoBuf.IExtensible
  {
    public RspExitArena() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyExitArena")]
  public partial class NotifyExitArena : global::ProtoBuf.IExtensible
  {
    public NotifyExitArena() {}
    
    private uint _characterid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}