//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/battlesync.proto
// Note: requires additional types generated from: common.proto
namespace proto.battlesync
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCharacterMove")]
  public partial class ReqCharacterMove : global::ProtoBuf.IExtensible
  {
    public ReqCharacterMove() {}
    
    private common.Vector _dest = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public common.Vector dest
    {
      get { return _dest; }
      set { _dest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyCharacterMove")]
  public partial class NotifyCharacterMove : global::ProtoBuf.IExtensible
  {
    public NotifyCharacterMove() {}
    
    private uint _characterid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private common.Vector _position = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public common.Vector position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyCharacterIdle")]
  public partial class NotifyCharacterIdle : global::ProtoBuf.IExtensible
  {
    public NotifyCharacterIdle() {}
    
    private uint _characterid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private common.Vector _pos = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public common.Vector pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCharacterAttack")]
  public partial class ReqCharacterAttack : global::ProtoBuf.IExtensible
  {
    public ReqCharacterAttack() {}
    
    private uint _skillid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private uint _targetID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint targetID
    {
      get { return _targetID; }
      set { _targetID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyCharacterAttack")]
  public partial class NotifyCharacterAttack : global::ProtoBuf.IExtensible
  {
    public NotifyCharacterAttack() {}
    
    private uint _characterid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private uint _targetid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint targetid
    {
      get { return _targetid; }
      set { _targetid = value; }
    }
    private uint _skillid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private common.Vector _pos = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public common.Vector pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyHPChange")]
  public partial class NotifyHPChange : global::ProtoBuf.IExtensible
  {
    public NotifyHPChange() {}
    
    private uint _targetid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint targetid
    {
      get { return _targetid; }
      set { _targetid = value; }
    }
    private int _hp = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyCharacterDie")]
  public partial class NotifyCharacterDie : global::ProtoBuf.IExtensible
  {
    public NotifyCharacterDie() {}
    
    private uint _characterid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}