//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/battlescene.proto
// Note: requires additional types generated from: common.proto
namespace proto.battlescene
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqEnterMap")]
  public partial class ReqEnterMap : global::ProtoBuf.IExtensible
  {
    public ReqEnterMap() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspEnterMap")]
  public partial class RspEnterMap : global::ProtoBuf.IExtensible
  {
    public RspEnterMap() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyCharacterExitMap")]
  public partial class NotifyCharacterExitMap : global::ProtoBuf.IExtensible
  {
    public NotifyCharacterExitMap() {}
    
    private int _characterid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyCharacterOnline")]
  public partial class NotifyCharacterOnline : global::ProtoBuf.IExtensible
  {
    public NotifyCharacterOnline() {}
    
    private common.CharacterDTO _character;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"character", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public common.CharacterDTO character
    {
      get { return _character; }
      set { _character = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSceneCharacters")]
  public partial class ReqSceneCharacters : global::ProtoBuf.IExtensible
  {
    public ReqSceneCharacters() {}
    
    private int _characterid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespSceneCharacters")]
  public partial class RespSceneCharacters : global::ProtoBuf.IExtensible
  {
    public RespSceneCharacters() {}
    
    private readonly global::System.Collections.Generic.List<common.CharacterDTO> _characters = new global::System.Collections.Generic.List<common.CharacterDTO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"characters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<common.CharacterDTO> characters
    {
      get { return _characters; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyCharacterOffline")]
  public partial class NotifyCharacterOffline : global::ProtoBuf.IExtensible
  {
    public NotifyCharacterOffline() {}
    
    private int _characterid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}