//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/character.proto
// Note: requires additional types generated from: common.proto
namespace proto.character
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCharactersInfo")]
  public partial class ReqCharactersInfo : global::ProtoBuf.IExtensible
  {
    public ReqCharactersInfo() {}
    
    private int _characterid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespCharactersInfo")]
  public partial class RespCharactersInfo : global::ProtoBuf.IExtensible
  {
    public RespCharactersInfo() {}
    
    private readonly global::System.Collections.Generic.List<common.CharacterDTO> _characters = new global::System.Collections.Generic.List<common.CharacterDTO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"characters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<common.CharacterDTO> characters
    {
      get { return _characters; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAddCharacter")]
  public partial class ReqAddCharacter : global::ProtoBuf.IExtensible
  {
    public ReqAddCharacter() {}
    
    private common.CharacterDTO _character;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"character", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public common.CharacterDTO character
    {
      get { return _character; }
      set { _character = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespAddCharacter")]
  public partial class RespAddCharacter : global::ProtoBuf.IExtensible
  {
    public RespAddCharacter() {}
    
    private uint _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private common.CharacterDTO _character;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"character", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public common.CharacterDTO character
    {
      get { return _character; }
      set { _character = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCharacterOnline")]
  public partial class ReqCharacterOnline : global::ProtoBuf.IExtensible
  {
    public ReqCharacterOnline() {}
    
    private int _characterid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private int _msgtips;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespCharacterOnline")]
  public partial class RespCharacterOnline : global::ProtoBuf.IExtensible
  {
    public RespCharacterOnline() {}
    
    private int _characterid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private int _msgtips;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCharacterOffline")]
  public partial class ReqCharacterOffline : global::ProtoBuf.IExtensible
  {
    public ReqCharacterOffline() {}
    
    private uint _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespCharacterOffline")]
  public partial class RespCharacterOffline : global::ProtoBuf.IExtensible
  {
    public RespCharacterOffline() {}
    
    private uint _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqDeleteCharacter")]
  public partial class ReqDeleteCharacter : global::ProtoBuf.IExtensible
  {
    public ReqDeleteCharacter() {}
    
    private int _characterid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespDeleteCharacter")]
  public partial class RespDeleteCharacter : global::ProtoBuf.IExtensible
  {
    public RespDeleteCharacter() {}
    
    private uint _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}