//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/inventory.proto
// Note: requires additional types generated from: common.proto
namespace proto.inventory
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetItemInfo")]
  public partial class ReqGetItemInfo : global::ProtoBuf.IExtensible
  {
    public ReqGetItemInfo() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespItemInfos")]
  public partial class RespItemInfos : global::ProtoBuf.IExtensible
  {
    public RespItemInfos() {}
    
    private readonly global::System.Collections.Generic.List<common.InventoryDTO> _inventorys = new global::System.Collections.Generic.List<common.InventoryDTO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"inventorys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<common.InventoryDTO> inventorys
    {
      get { return _inventorys; }
    }
  
    private readonly global::System.Collections.Generic.List<common.InventoryDTO> _equips = new global::System.Collections.Generic.List<common.InventoryDTO>();
    [global::ProtoBuf.ProtoMember(2, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<common.InventoryDTO> equips
    {
      get { return _equips; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqEquipItem")]
  public partial class ReqEquipItem : global::ProtoBuf.IExtensible
  {
    public ReqEquipItem() {}
    
    private int _slot;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int slot
    {
      get { return _slot; }
      set { _slot = value; }
    }
    private int _itemid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespEquipItem")]
  public partial class RespEquipItem : global::ProtoBuf.IExtensible
  {
    public RespEquipItem() {}
    
    private common.InventoryDTO _equip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public common.InventoryDTO equip
    {
      get { return _equip; }
      set { _equip = value; }
    }
    private common.InventoryDTO _inv;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"inv", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public common.InventoryDTO inv
    {
      get { return _inv; }
      set { _inv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqUnloadItem")]
  public partial class ReqUnloadItem : global::ProtoBuf.IExtensible
  {
    public ReqUnloadItem() {}
    
    private int _slot;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int slot
    {
      get { return _slot; }
      set { _slot = value; }
    }
    private int _itemid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespUnloadItem")]
  public partial class RespUnloadItem : global::ProtoBuf.IExtensible
  {
    public RespUnloadItem() {}
    
    private common.InventoryDTO _equip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public common.InventoryDTO equip
    {
      get { return _equip; }
      set { _equip = value; }
    }
    private common.InventoryDTO _inv;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"inv", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public common.InventoryDTO inv
    {
      get { return _inv; }
      set { _inv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqDeleteItem")]
  public partial class ReqDeleteItem : global::ProtoBuf.IExtensible
  {
    public ReqDeleteItem() {}
    
    private DeleteType _deleteType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"deleteType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public DeleteType deleteType
    {
      get { return _deleteType; }
      set { _deleteType = value; }
    }
    private int _slot;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int slot
    {
      get { return _slot; }
      set { _slot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespDeleteItem")]
  public partial class RespDeleteItem : global::ProtoBuf.IExtensible
  {
    public RespDeleteItem() {}
    
    private DeleteType _deleteType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"deleteType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public DeleteType deleteType
    {
      get { return _deleteType; }
      set { _deleteType = value; }
    }
    private common.InventoryDTO _dto;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public common.InventoryDTO dto
    {
      get { return _dto; }
      set { _dto = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"DeleteType")]
    public enum DeleteType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Equip", Value=1)]
      Equip = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Inv", Value=2)]
      Inv = 2
    }
  
}