//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/mall.proto
// Note: requires additional types generated from: common.proto
namespace proto.mall
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqMallInfo")]
  public partial class ReqMallInfo : global::ProtoBuf.IExtensible
  {
    public ReqMallInfo() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspMallInfo")]
  public partial class RspMallInfo : global::ProtoBuf.IExtensible
  {
    public RspMallInfo() {}
    
    private readonly global::System.Collections.Generic.List<uint> _goods = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"goods", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> goods
    {
      get { return _goods; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBuyGoods")]
  public partial class ReqBuyGoods : global::ProtoBuf.IExtensible
  {
    public ReqBuyGoods() {}
    
    private uint _goodid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"goodid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint goodid
    {
      get { return _goodid; }
      set { _goodid = value; }
    }
    private BuyType _buyType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"buyType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BuyType buyType
    {
      get { return _buyType; }
      set { _buyType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspBuyGoods")]
  public partial class RspBuyGoods : global::ProtoBuf.IExtensible
  {
    public RspBuyGoods() {}
    
    private uint _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private common.InventoryDTO _inv;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"inv", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public common.InventoryDTO inv
    {
      get { return _inv; }
      set { _inv = value; }
    }
    private uint _gold;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private uint _diamond;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"BuyType")]
    public enum BuyType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gold", Value=0)]
      Gold = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Diamon", Value=1)]
      Diamon = 1
    }
  
}