//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/battledungeon.proto
// Note: requires additional types generated from: common.proto
namespace proto.battledungeon
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqMatchDungeon")]
  public partial class ReqMatchDungeon : global::ProtoBuf.IExtensible
  {
    public ReqMatchDungeon() {}
    
    private uint _mapid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspMatchDungeon")]
  public partial class RspMatchDungeon : global::ProtoBuf.IExtensible
  {
    public RspMatchDungeon() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCancelMatchDungeon")]
  public partial class ReqCancelMatchDungeon : global::ProtoBuf.IExtensible
  {
    public ReqCancelMatchDungeon() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspCancelMatchDungeon")]
  public partial class RspCancelMatchDungeon : global::ProtoBuf.IExtensible
  {
    public RspCancelMatchDungeon() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyMatchComplete")]
  public partial class NotifyMatchComplete : global::ProtoBuf.IExtensible
  {
    public NotifyMatchComplete() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqStartDungeon")]
  public partial class ReqStartDungeon : global::ProtoBuf.IExtensible
  {
    public ReqStartDungeon() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspStartDungeon")]
  public partial class RspStartDungeon : global::ProtoBuf.IExtensible
  {
    public RspStartDungeon() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RepEnterDungeon")]
  public partial class RepEnterDungeon : global::ProtoBuf.IExtensible
  {
    public RepEnterDungeon() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyPlayerEnterDungeon")]
  public partial class NotifyPlayerEnterDungeon : global::ProtoBuf.IExtensible
  {
    public NotifyPlayerEnterDungeon() {}
    
    private readonly global::System.Collections.Generic.List<common.CharacterDTO> _chs = new global::System.Collections.Generic.List<common.CharacterDTO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"chs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<common.CharacterDTO> chs
    {
      get { return _chs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqExitDungeon")]
  public partial class ReqExitDungeon : global::ProtoBuf.IExtensible
  {
    public ReqExitDungeon() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RspExitDungeon")]
  public partial class RspExitDungeon : global::ProtoBuf.IExtensible
  {
    public RspExitDungeon() {}
    
    private common.MsgTips _msgtips;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.MsgTips msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyExitDungeon")]
  public partial class NotifyExitDungeon : global::ProtoBuf.IExtensible
  {
    public NotifyExitDungeon() {}
    
    private uint _characterid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}