//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/mail.proto
// Note: requires additional types generated from: common.proto
namespace proto.mail
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqMailInfos")]
  public partial class ReqMailInfos : global::ProtoBuf.IExtensible
  {
    public ReqMailInfos() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespMailInfos")]
  public partial class RespMailInfos : global::ProtoBuf.IExtensible
  {
    public RespMailInfos() {}
    
    private readonly global::System.Collections.Generic.List<common.MailDTO> _mails = new global::System.Collections.Generic.List<common.MailDTO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mails", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<common.MailDTO> mails
    {
      get { return _mails; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqDeleteMail")]
  public partial class ReqDeleteMail : global::ProtoBuf.IExtensible
  {
    public ReqDeleteMail() {}
    
    private int _characterid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"characterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int characterid
    {
      get { return _characterid; }
      set { _characterid = value; }
    }
    private int _mailid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mailid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailid
    {
      get { return _mailid; }
      set { _mailid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespDeleteMail")]
  public partial class RespDeleteMail : global::ProtoBuf.IExtensible
  {
    public RespDeleteMail() {}
    
    private int _mailid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mailid
    {
      get { return _mailid; }
      set { _mailid = value; }
    }
    private int _msgtips;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msgtips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int msgtips
    {
      get { return _msgtips; }
      set { _msgtips = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSendMail")]
  public partial class ReqSendMail : global::ProtoBuf.IExtensible
  {
    public ReqSendMail() {}
    
    private common.MailDTO _dto;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public common.MailDTO dto
    {
      get { return _dto; }
      set { _dto = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespSendMail")]
  public partial class RespSendMail : global::ProtoBuf.IExtensible
  {
    public RespSendMail() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRecvItem")]
  public partial class ReqRecvItem : global::ProtoBuf.IExtensible
  {
    public ReqRecvItem() {}
    
    private int _mail_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mail_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mail_id
    {
      get { return _mail_id; }
      set { _mail_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespRecvItem")]
  public partial class RespRecvItem : global::ProtoBuf.IExtensible
  {
    public RespRecvItem() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}