-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('account_pb')


local REQREGISTER = protobuf.Descriptor();
local REQREGISTER_ACCOUNT_FIELD = protobuf.FieldDescriptor();
local REQREGISTER_PASSWORD_FIELD = protobuf.FieldDescriptor();
local RESPREGISTER = protobuf.Descriptor();
local RESPREGISTER_MSGTIPS_FIELD = protobuf.FieldDescriptor();
local REQLOGIN = protobuf.Descriptor();
local REQLOGIN_ACCOUNT_FIELD = protobuf.FieldDescriptor();
local REQLOGIN_PASSWORD_FIELD = protobuf.FieldDescriptor();
local RESPLOGIN = protobuf.Descriptor();
local RESPLOGIN_ACCOUNT_FIELD = protobuf.FieldDescriptor();
local RESPLOGIN_MSGTIPS_FIELD = protobuf.FieldDescriptor();
local REQOFFLINE = protobuf.Descriptor();
local RESPOFFLINE = protobuf.Descriptor();
local RESPOFFLINE_MSGTIPS_FIELD = protobuf.FieldDescriptor();

REQREGISTER_ACCOUNT_FIELD.name = "account"
REQREGISTER_ACCOUNT_FIELD.full_name = ".account.ReqRegister.account"
REQREGISTER_ACCOUNT_FIELD.number = 1
REQREGISTER_ACCOUNT_FIELD.index = 0
REQREGISTER_ACCOUNT_FIELD.label = 2
REQREGISTER_ACCOUNT_FIELD.has_default_value = false
REQREGISTER_ACCOUNT_FIELD.default_value = ""
REQREGISTER_ACCOUNT_FIELD.type = 9
REQREGISTER_ACCOUNT_FIELD.cpp_type = 9

REQREGISTER_PASSWORD_FIELD.name = "password"
REQREGISTER_PASSWORD_FIELD.full_name = ".account.ReqRegister.password"
REQREGISTER_PASSWORD_FIELD.number = 2
REQREGISTER_PASSWORD_FIELD.index = 1
REQREGISTER_PASSWORD_FIELD.label = 2
REQREGISTER_PASSWORD_FIELD.has_default_value = false
REQREGISTER_PASSWORD_FIELD.default_value = ""
REQREGISTER_PASSWORD_FIELD.type = 9
REQREGISTER_PASSWORD_FIELD.cpp_type = 9

REQREGISTER.name = "ReqRegister"
REQREGISTER.full_name = ".account.ReqRegister"
REQREGISTER.nested_types = {}
REQREGISTER.enum_types = {}
REQREGISTER.fields = {REQREGISTER_ACCOUNT_FIELD, REQREGISTER_PASSWORD_FIELD}
REQREGISTER.is_extendable = false
REQREGISTER.extensions = {}
RESPREGISTER_MSGTIPS_FIELD.name = "msgtips"
RESPREGISTER_MSGTIPS_FIELD.full_name = ".account.RespRegister.msgtips"
RESPREGISTER_MSGTIPS_FIELD.number = 1
RESPREGISTER_MSGTIPS_FIELD.index = 0
RESPREGISTER_MSGTIPS_FIELD.label = 2
RESPREGISTER_MSGTIPS_FIELD.has_default_value = false
RESPREGISTER_MSGTIPS_FIELD.default_value = 0
RESPREGISTER_MSGTIPS_FIELD.type = 13
RESPREGISTER_MSGTIPS_FIELD.cpp_type = 3

RESPREGISTER.name = "RespRegister"
RESPREGISTER.full_name = ".account.RespRegister"
RESPREGISTER.nested_types = {}
RESPREGISTER.enum_types = {}
RESPREGISTER.fields = {RESPREGISTER_MSGTIPS_FIELD}
RESPREGISTER.is_extendable = false
RESPREGISTER.extensions = {}
REQLOGIN_ACCOUNT_FIELD.name = "account"
REQLOGIN_ACCOUNT_FIELD.full_name = ".account.ReqLogin.account"
REQLOGIN_ACCOUNT_FIELD.number = 1
REQLOGIN_ACCOUNT_FIELD.index = 0
REQLOGIN_ACCOUNT_FIELD.label = 2
REQLOGIN_ACCOUNT_FIELD.has_default_value = false
REQLOGIN_ACCOUNT_FIELD.default_value = ""
REQLOGIN_ACCOUNT_FIELD.type = 9
REQLOGIN_ACCOUNT_FIELD.cpp_type = 9

REQLOGIN_PASSWORD_FIELD.name = "password"
REQLOGIN_PASSWORD_FIELD.full_name = ".account.ReqLogin.password"
REQLOGIN_PASSWORD_FIELD.number = 2
REQLOGIN_PASSWORD_FIELD.index = 1
REQLOGIN_PASSWORD_FIELD.label = 2
REQLOGIN_PASSWORD_FIELD.has_default_value = false
REQLOGIN_PASSWORD_FIELD.default_value = ""
REQLOGIN_PASSWORD_FIELD.type = 9
REQLOGIN_PASSWORD_FIELD.cpp_type = 9

REQLOGIN.name = "ReqLogin"
REQLOGIN.full_name = ".account.ReqLogin"
REQLOGIN.nested_types = {}
REQLOGIN.enum_types = {}
REQLOGIN.fields = {REQLOGIN_ACCOUNT_FIELD, REQLOGIN_PASSWORD_FIELD}
REQLOGIN.is_extendable = false
REQLOGIN.extensions = {}
RESPLOGIN_ACCOUNT_FIELD.name = "account"
RESPLOGIN_ACCOUNT_FIELD.full_name = ".account.RespLogin.account"
RESPLOGIN_ACCOUNT_FIELD.number = 1
RESPLOGIN_ACCOUNT_FIELD.index = 0
RESPLOGIN_ACCOUNT_FIELD.label = 2
RESPLOGIN_ACCOUNT_FIELD.has_default_value = false
RESPLOGIN_ACCOUNT_FIELD.default_value = ""
RESPLOGIN_ACCOUNT_FIELD.type = 9
RESPLOGIN_ACCOUNT_FIELD.cpp_type = 9

RESPLOGIN_MSGTIPS_FIELD.name = "msgtips"
RESPLOGIN_MSGTIPS_FIELD.full_name = ".account.RespLogin.msgtips"
RESPLOGIN_MSGTIPS_FIELD.number = 2
RESPLOGIN_MSGTIPS_FIELD.index = 1
RESPLOGIN_MSGTIPS_FIELD.label = 2
RESPLOGIN_MSGTIPS_FIELD.has_default_value = false
RESPLOGIN_MSGTIPS_FIELD.default_value = 0
RESPLOGIN_MSGTIPS_FIELD.type = 13
RESPLOGIN_MSGTIPS_FIELD.cpp_type = 3

RESPLOGIN.name = "RespLogin"
RESPLOGIN.full_name = ".account.RespLogin"
RESPLOGIN.nested_types = {}
RESPLOGIN.enum_types = {}
RESPLOGIN.fields = {RESPLOGIN_ACCOUNT_FIELD, RESPLOGIN_MSGTIPS_FIELD}
RESPLOGIN.is_extendable = false
RESPLOGIN.extensions = {}
REQOFFLINE.name = "ReqOffline"
REQOFFLINE.full_name = ".account.ReqOffline"
REQOFFLINE.nested_types = {}
REQOFFLINE.enum_types = {}
REQOFFLINE.fields = {}
REQOFFLINE.is_extendable = false
REQOFFLINE.extensions = {}
RESPOFFLINE_MSGTIPS_FIELD.name = "msgtips"
RESPOFFLINE_MSGTIPS_FIELD.full_name = ".account.RespOffline.msgtips"
RESPOFFLINE_MSGTIPS_FIELD.number = 1
RESPOFFLINE_MSGTIPS_FIELD.index = 0
RESPOFFLINE_MSGTIPS_FIELD.label = 2
RESPOFFLINE_MSGTIPS_FIELD.has_default_value = false
RESPOFFLINE_MSGTIPS_FIELD.default_value = 0
RESPOFFLINE_MSGTIPS_FIELD.type = 13
RESPOFFLINE_MSGTIPS_FIELD.cpp_type = 3

RESPOFFLINE.name = "RespOffline"
RESPOFFLINE.full_name = ".account.RespOffline"
RESPOFFLINE.nested_types = {}
RESPOFFLINE.enum_types = {}
RESPOFFLINE.fields = {RESPOFFLINE_MSGTIPS_FIELD}
RESPOFFLINE.is_extendable = false
RESPOFFLINE.extensions = {}

ReqLogin = protobuf.Message(REQLOGIN)
ReqOffline = protobuf.Message(REQOFFLINE)
ReqRegister = protobuf.Message(REQREGISTER)
RespLogin = protobuf.Message(RESPLOGIN)
RespOffline = protobuf.Message(RESPOFFLINE)
RespRegister = protobuf.Message(RESPREGISTER)

