-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local common_pb = require("common_pb")
module('friend_pb')


local REQFRIENDLIST = protobuf.Descriptor();
local REQFRIENDLIST_CHARACTERID_FIELD = protobuf.FieldDescriptor();
local RSPFRIENDLIST = protobuf.Descriptor();
local RSPFRIENDLIST_INFOS_FIELD = protobuf.FieldDescriptor();
local REQADDFRIEND = protobuf.Descriptor();
local REQADDFRIEND_CHARACTERID_FIELD = protobuf.FieldDescriptor();

REQFRIENDLIST_CHARACTERID_FIELD.name = "characterid"
REQFRIENDLIST_CHARACTERID_FIELD.full_name = ".ReqFriendList.characterid"
REQFRIENDLIST_CHARACTERID_FIELD.number = 1
REQFRIENDLIST_CHARACTERID_FIELD.index = 0
REQFRIENDLIST_CHARACTERID_FIELD.label = 2
REQFRIENDLIST_CHARACTERID_FIELD.has_default_value = false
REQFRIENDLIST_CHARACTERID_FIELD.default_value = 0
REQFRIENDLIST_CHARACTERID_FIELD.type = 5
REQFRIENDLIST_CHARACTERID_FIELD.cpp_type = 1

REQFRIENDLIST.name = "ReqFriendList"
REQFRIENDLIST.full_name = ".ReqFriendList"
REQFRIENDLIST.nested_types = {}
REQFRIENDLIST.enum_types = {}
REQFRIENDLIST.fields = {REQFRIENDLIST_CHARACTERID_FIELD}
REQFRIENDLIST.is_extendable = false
REQFRIENDLIST.extensions = {}
RSPFRIENDLIST_INFOS_FIELD.name = "infos"
RSPFRIENDLIST_INFOS_FIELD.full_name = ".RspFriendList.infos"
RSPFRIENDLIST_INFOS_FIELD.number = 1
RSPFRIENDLIST_INFOS_FIELD.index = 0
RSPFRIENDLIST_INFOS_FIELD.label = 3
RSPFRIENDLIST_INFOS_FIELD.has_default_value = false
RSPFRIENDLIST_INFOS_FIELD.default_value = {}
RSPFRIENDLIST_INFOS_FIELD.message_type = COMMON_PB_FRIENDINFO
RSPFRIENDLIST_INFOS_FIELD.type = 11
RSPFRIENDLIST_INFOS_FIELD.cpp_type = 10

RSPFRIENDLIST.name = "RspFriendList"
RSPFRIENDLIST.full_name = ".RspFriendList"
RSPFRIENDLIST.nested_types = {}
RSPFRIENDLIST.enum_types = {}
RSPFRIENDLIST.fields = {RSPFRIENDLIST_INFOS_FIELD}
RSPFRIENDLIST.is_extendable = false
RSPFRIENDLIST.extensions = {}
REQADDFRIEND_CHARACTERID_FIELD.name = "characterid"
REQADDFRIEND_CHARACTERID_FIELD.full_name = ".ReqAddFriend.characterid"
REQADDFRIEND_CHARACTERID_FIELD.number = 1
REQADDFRIEND_CHARACTERID_FIELD.index = 0
REQADDFRIEND_CHARACTERID_FIELD.label = 2
REQADDFRIEND_CHARACTERID_FIELD.has_default_value = false
REQADDFRIEND_CHARACTERID_FIELD.default_value = 0
REQADDFRIEND_CHARACTERID_FIELD.type = 5
REQADDFRIEND_CHARACTERID_FIELD.cpp_type = 1

REQADDFRIEND.name = "ReqAddFriend"
REQADDFRIEND.full_name = ".ReqAddFriend"
REQADDFRIEND.nested_types = {}
REQADDFRIEND.enum_types = {}
REQADDFRIEND.fields = {REQADDFRIEND_CHARACTERID_FIELD}
REQADDFRIEND.is_extendable = false
REQADDFRIEND.extensions = {}

ReqAddFriend = protobuf.Message(REQADDFRIEND)
ReqFriendList = protobuf.Message(REQFRIENDLIST)
RspFriendList = protobuf.Message(RSPFRIENDLIST)

