//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ByteArrayWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ByteArray), typeof(System.Object));
		L.RegFunction("Close", Close);
		L.RegFunction("write", write);
		L.RegFunction("read", read);
		L.RegFunction("reposition", reposition);
		L.RegFunction("getBuff", getBuff);
		L.RegFunction("GetBuffer", GetBuffer);
		L.RegFunction("New", _CreateByteArray);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Position", get_Position, null);
		L.RegVar("Length", get_Length, null);
		L.RegVar("Readnable", get_Readnable, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateByteArray(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ByteArray obj = new ByteArray();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1)
			{
				byte[] arg0 = ToLua.CheckByteBuffer(L, 1);
				ByteArray obj = new ByteArray(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ByteArray.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Close(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
			obj.Close();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int write(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<double>(L, 2))
			{
				ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
				double arg0 = (double)LuaDLL.lua_tonumber(L, 2);
				obj.write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<long>(L, 2))
			{
				ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
				long arg0 = LuaDLL.tolua_toint64(L, 2);
				obj.write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<byte[]>(L, 2))
			{
				ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
				byte[] arg0 = ToLua.CheckByteBuffer(L, 2);
				obj.write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<bool>(L, 2))
			{
				ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
				bool arg0 = LuaDLL.lua_toboolean(L, 2);
				obj.write(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				obj.write(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: ByteArray.write");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int read(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<LuaInterface.LuaOut<double>>(L, 2))
			{
				ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
				double arg0;
				obj.read(out arg0);
				LuaDLL.lua_pushnumber(L, arg0);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<LuaInterface.LuaOut<float>>(L, 2))
			{
				ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
				float arg0;
				obj.read(out arg0);
				LuaDLL.lua_pushnumber(L, arg0);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<LuaInterface.LuaOut<long>>(L, 2))
			{
				ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
				long arg0;
				obj.read(out arg0);
				LuaDLL.tolua_pushint64(L, arg0);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<LuaInterface.LuaOut<string>>(L, 2))
			{
				ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
				string arg0 = null;
				obj.read(out arg0);
				LuaDLL.lua_pushstring(L, arg0);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<LuaInterface.LuaOut<byte>>(L, 2))
			{
				ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
				byte arg0;
				obj.read(out arg0);
				LuaDLL.lua_pushnumber(L, arg0);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<LuaInterface.LuaOut<int>>(L, 2))
			{
				ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
				int arg0;
				obj.read(out arg0);
				LuaDLL.lua_pushinteger(L, arg0);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<LuaInterface.LuaOut<bool>>(L, 2))
			{
				ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
				bool arg0;
				obj.read(out arg0);
				LuaDLL.lua_pushboolean(L, arg0);
				return 1;
			}
			else if (count == 3)
			{
				ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
				byte[] arg0 = null;
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				obj.read(out arg0, arg1);
				ToLua.Push(L, arg0);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: ByteArray.read");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int reposition(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
			obj.reposition();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getBuff(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ByteArray obj = (ByteArray)ToLua.CheckObject<ByteArray>(L, 1);
			byte[] o = obj.getBuff();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBuffer(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			byte[] arg0 = ToLua.CheckByteBuffer(L, 1);
			LuaInterface.LuaByteBuffer o = ByteArray.GetBuffer(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Position(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ByteArray obj = (ByteArray)o;
			int ret = obj.Position;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Position on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Length(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ByteArray obj = (ByteArray)o;
			int ret = obj.Length;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Length on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Readnable(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ByteArray obj = (ByteArray)o;
			bool ret = obj.Readnable;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Readnable on a nil value");
		}
	}
}

